### ISSUE TITLE
Are there any plans to make it compatible? (Intellij 2022.3 version)

### ISSUE THREAD

**Issue by molrang** [gejun123456/IbatisCodeHelperIssues#1]
hello
I am using this plugin well.
This is the only plugin that works in ibatis.
Are there any plans to enable compatibility with Intellij 2022.3 version?
thx

**Comment by gejun123456** [comment]
[IbatisCodeHelperNew-1.0.3.zip](https://github.com/gejun123456/IbatisCodeHelperIssues/files/10163457/IbatisCodeHelperNew-1.0.3.zip)
can you help try this version to see if it works, thanks.

**Comment by molrang** [comment]
It works. thank you.
